server:
  port: 8080
application:
  databases:
    h2-first_db:
      url: jdbc:h2:tcp://localhost/~/test
      user: sa
      password:
      driverClassName: org.h2.Driver
    h2-second_db:
      url: jdbc:h2:tcp://localhost/~/test2
      user: sa
      password:
      driverClassName: org.h2.Driver
    h2-third_db:
      url: jdbc:h2:tcp://localhost/~/test3
      user: sa
      password:
      driverClassName: org.h2.Driver
